package Clases;

public enum Diagnostico {

	HIPOPOTASEMIA,
	HIPOCALCEMIA,
	INFARTO_AGUDO_MIOCARDIO,
	ISQUEMIA_CORONARIA,
	BRADICARDIA_SINUSAL,
	TAQUICARDIA_SINUSAL,
	FLUTTER_AURICULAR,
	CONTRACCION,VENTRICULAR_PREMATURA,
	SANO
}
